### ISSUE TITLE
Follow for follow

### ISSUE THREAD

**Issue by s0lvang** [Paalar/friendly-enigma#3]
Both I and Aslak, the main contributers for https://github.com/s0lvang/ideal-pancake have starred this project. Please star back

**Comment by aslakhol** [comment]
I agree with @s0lvang. Great issue!

**Comment by aslakhol** [comment]
This seems to have been resolved, you can close this issue now. 

![image](https://user-images.githubusercontent.com/11901064/101168816-49dba080-363c-11eb-9ac9-8ee74ac6d817.png)

**Comment by johanneskvamme** [comment]
Resolved by follow
